# Generated by Django 5.1.2 on 2024-10-20 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='weld_info',
            name='seleted',
            field=models.BooleanField(default=1),
            preserve_default=False,
        ),
    ]
