# Generated by Django 5.1.2 on 2024-10-23 08:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weld', '0004_weld_raw_data_after_result_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='weld_info',
            name='selected',
        ),
    ]
